server:
  port: ${PORT:5001}

base-url: /api

spring:
  application:
    name: my-task-tracker
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate